### ISSUE TITLE
Jail package

### ISSUE THREAD

**Issue by zachfi** [briandowns/sky-island#33]
Hi. Why not use your other jail pacakge here?  I'm looking for a jail handler in go, and you have two :)

**Comment by briandowns** [comment]
Thanks for looking through these projects! I intend to get it integrated however I just haven't had time. Hopefully soon.

**Comment by xaque208** [comment]
So if I were to try and work on one, is there a preference, from your perspective?  I saw your presentation on sky-island at BSDCAN, but I think I just want a jail manager in go, so probably the bindings are where I'd lean.  I have zero experience working with bindings though, so it would be a learning process for me.

**Comment by briandowns** [comment]
Oh cool. I was stupid nervous. As for a jail manager in Go, I would likely say that looking at iocage and porting might be the best option and only keeping what you think would be relevant for you. I heard a rumor they were going to do a rewrite in Go. I have a few other naive repos for examples and uses: https://github.com/briandowns/gail, and I started on this one: https://github.com/briandowns/jail-builder

**Comment by xaque208** [comment]
I would contribute to such a project.  I've been using iocage since early days of the /bin/sh version.  From my perspective, the project has not been well-managed.  The removal of the shell version of the port before the python port existed caused me lots of grief, and that there has not been a release in quite some time but many fixes keep going in, as well as two tools that do the same thing, just in python.  One being the library and one being the cli, but the library also has a cli.  Its not clear the direction.

In any case, I'm not looking to boil the ocean or anything, but something to get some jails running and configured network stacks would be great.  From lurking on the iocage repo for the last couple years, many of the runtime issues that have been encountered could be avoided with strong typing.  Also, I've been writing almost exclusively in Go for the last couple years.

I'll have a look at those other projects you mention.  Seems like you also have an interest in this area, ye with 4 jail management tools :)
